<?php 
/************************************************
 Sphider-plus version 3.2015a authentication file.

 > > >  DO NOT EDIT THIS FILE. < < < 

Any modification must be done by Admin settings. 
*************************************************/

/******************************* Check for forbidden direct access ************************************/

    if (!defined('_SECURE')) die ("No direct access to authentication file");

/*********************** 
Admin access 
***********************/
   $admin       = '$1$NI1.Sb4.$DCEuhoqvZBd2ZFzXF8YlM.';
   $admin_pw    = '$1$zS4.Au..$LdnigOZfxLdVL3WbJYx79/';

/*********************** 
Database access 
***********************/
   $db_admin    = '$1$nK2.kR4.$yM4LL1/M04T7InmOybTSq.';
   $db_admin_pw = '$1$df3.iB4.$3k..mjaoQdlWeLocKs9xm/';

?>