<?php 
/************************************************
 Sphider-plus version 3.2015d authentication file.

 > > >  DO NOT EDIT THIS FILE. < < < 

Any modification must be done by Admin settings. 
*************************************************/

/******************************* Check for forbidden direct access ************************************/

    if (!defined('_SECURE')) die ("No direct access to authentication file");

/*********************** 
Admin access 
***********************/
   $admin       = '$1$J03.eK4.$31JPccMPqgQfsH6zQzWJX/';
   $admin_pw    = '$1$PK2.so..$woea01HzyiOhngL3m4dhE1';

/*********************** 
Database access 
***********************/
   $db_admin    = '$1$bM/.I1..$gqpmCxcmQdrTgrOtKZYdC/';
   $db_admin_pw = '$1$x70.mJ5.$s0KOjkIATcz7xRx/f07PK1';

?>